# Generated by Django 5.2.17 on 2026-10-03 09:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_legacy_attempts(apps, schema_editor):
    Submission = apps.get_model('api', 'Submission')
    from django.db.models import Count
    duplicates = Submission.objects.values('assignment_id', 'student_id', 'attempt').annotate(n=Count('id')).filter(n__gt=1)
    pairs = {(r['assignment_id'], r['student_id']) for r in duplicates}
    for assignment_id, student_id in pairs:
        rows = Submission.objects.filter(assignment_id=assignment_id, student_id=student_id).order_by('submitted_at', 'id')
        for attempt, row in enumerate(rows, 1):
            Submission.objects.filter(pk=row.pk).update(attempt=attempt)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_bio_user_email_alter_user_birthday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Qatnashdi'), ('absent', 'Qatnashmadi'), ('late', 'Kechikdi'), ('excused', 'Sababli')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('topic', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at', '-id']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='allow_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(normalize_legacy_attempts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student', 'attempt'), name='unique_submission_attempt'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.attendancesession'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='api.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='api.course'),
        ),
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='api.course'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.course'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='unique_attendance_record'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('course', 'starts_at'), name='unique_course_session'),
        ),
    ]
