# Generated by Django 5.2.17 on 2026-10-04 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='location_accuracy_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Qo‘lda'), ('qr', 'QR'), ('ultrasound', 'Ultrasound'), ('system', 'Tizim')], default='manual', max_length=12),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='attendance_minutes',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='automated_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='late_after_minutes',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='location_radius_m',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='max_location_accuracy_m',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
