# Generated by Django 5.2.17 on 2026-10-04 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_must_change_password_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='calendar_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_session', to='api.calendarevent'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
