# Generated by Django 5.2.17 on 2026-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attendancesession_calendar_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
