# Generated by Django 5.2.17 on 2026-10-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='presence_samples',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
