# Generated by Django 5.2.17 on 2026-10-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_attendancerecord_last_seen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='presence_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
