# Generated by Django 5.2.17 on 2026-10-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_attendancerecord_presence_alerted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
