# Generated by Django 5.2.17 on 2026-10-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_attendancesession_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAttemptWindow',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('window', models.BigIntegerField()),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Qo‘lda'), ('qr', 'QR'), ('ultrasound', 'Ultrasound'), ('manual_code', 'Qisqa kod'), ('system', 'Tizim')], default='manual', max_length=12),
        ),
    ]
