"use client"
import {useEffect,useState} from "react"
import Link from "next/link"
import {ArrowRight,ArrowUpRight,BookOpen,ClipboardList,CalendarDays,ChartNoAxesCombined,Clock,Check,FileText,ChevronRight,GraduationCap} from "lucide-react"
import {getBooks,getAssignments,getMyGrades,getCalendar} from "@/lib/api-service"
import {useAuth} from "@/contexts/auth-context"
import {Button} from "@/components/ui/button"
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog"
import {Alert,AlertDescription} from "@/components/ui/alert"
const dateLabel=(date:string)=>new Date(date).toLocaleDateString("uz-UZ",{day:"numeric",month:"short",timeZone:"Asia/Tashkent"})
const demoBooks=[{id:1,title:"Dasturlash asoslari",subject:"Axborot texnologiyalari",uploaded_at:"2026-10-01"},{id:2,title:"Biznes muloqot",subject:"Umumiy fanlar",uploaded_at:"2026-10-02"},{id:3,title:"Ingliz tili",subject:"Xorijiy tillar",uploaded_at:"2026-10-02"}]
const demoAssignments=[{id:1,title:"Python: shart operatorlari",description:"Shart operatorlari yordamida masalalar yeching va javob faylini topshiring.",due_date:"2026-10-05T18:00:00+05:00",is_submitted:false},{id:2,title:"Rasmiy xat yozish",description:"Biznes muloqot qoidalariga mos rasmiy xat tayyorlang.",due_date:"2026-10-07T18:00:00+05:00",is_submitted:false},{id:3,title:"Reading & vocabulary",description:"O‘quv matni asosida lug‘at topshiriqlarini bajaring.",due_date:"2026-10-08T18:00:00+05:00",is_submitted:true}]
const demoEvents=[{id:1,title:"Dasturlash asoslari",start_date:"2026-10-05T09:00:00+05:00",end_date:"2026-10-05T10:20:00+05:00",description:"Amaliy mashg‘ulot"},{id:2,title:"Biznes muloqot",start_date:"2026-10-05T10:30:00+05:00",end_date:"2026-10-05T11:50:00+05:00",description:"Seminar"}]
export function LMSDashboard({demo=false}:{demo?:boolean}){
 const {user}=useAuth(),[books,setBooks]=useState<any[]>(demo?demoBooks:[]),[assignments,setAssignments]=useState<any[]>(demo?demoAssignments:[]),[grades,setGrades]=useState<any[]>(demo?[{id:1,grade:92,assignment:{title:"Dasturlash asoslari"}},{id:2,grade:88,assignment:{title:"Biznes muloqot"}}]:[]),[events,setEvents]=useState<any[]>(demo?demoEvents:[]),[loading,setLoading]=useState(!demo),[error,setError]=useState(""),[detail,setDetail]=useState<any>(null)
 useEffect(()=>{if(demo)return;let active=true;Promise.all([getBooks(),getAssignments(),getMyGrades(),getCalendar()]).then(([b,a,g,e])=>{if(active){setBooks(b);setAssignments(a);setGrades(g);setEvents(e)}}).catch(()=>active&&setError("Ma’lumotlarni yuklab bo‘lmadi. Sahifani yangilang yoki birozdan so‘ng qayta kiring.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[demo])
 const pending=assignments.filter(a=>!a.is_submitted),valid=grades.filter(g=>g.grade!==null&&g.grade!==undefined),average=valid.length?Math.round(valid.reduce((s,g)=>s+Number(g.grade),0)/valid.length):null
 const upcoming=events.filter(e=>demo||new Date(e.start_date).getTime()>=Date.now()).sort((a,b)=>new Date(a.start_date).getTime()-new Date(b.start_date).getTime())
 const stats=[{label:"O‘quv materiallari",value:books.length,suffix:"ta material",icon:BookOpen,kind:"navy"},{label:"Faol topshiriqlar",value:pending.length,suffix:"ta kutilmoqda",icon:ClipboardList,kind:"gold"},{label:"O‘rtacha natija",value:average===null?"—":average,suffix:average===null?"hali baholanmagan":"/ 100 ball",icon:ChartNoAxesCombined,kind:"green"},{label:"Yaqin tadbirlar",value:upcoming.length,suffix:"ta rejalashtirilgan",icon:CalendarDays,kind:"purple"}]
 const action=(item:any,href:string)=>demo?<button className="item-action" onClick={()=>setDetail(item)} aria-label={`${item.title} — ko‘rish`}><ArrowUpRight size={19}/></button>:<Link className="item-action" href={href} aria-label={`${item.title} — ko‘rish`}><ArrowUpRight size={19}/></Link>
 return <main className="dashboard" id="overview"><div className="page-heading"><div><p className="eyebrow">BILIM SARI NAVBATDAGI QADAM</p><h1>Assalomu alaykum{user?.first_name?`, ${user.first_name}`:""}!</h1><p>Bugungi imkoniyatlar — ertangi yutuqlaringiz poydevori.</p></div><div className="date-chip"><CalendarDays size={16}/>{demo?"3-oktabr, 2026":new Date().toLocaleDateString("uz-UZ",{day:"numeric",month:"long",year:"numeric",timeZone:"Asia/Tashkent"})}</div></div>
 <section className="welcome-banner"><img src="/brand/campus.webp" alt="Millat Umidi universiteti kampusi"/><div className="banner-shade"/><div className="banner-copy"><div className="banner-kicker"><span/>MILLAT UMIDI UNIVERSITY</div><h2>Kelajagingizni<br/><em>bugundan yarating.</em></h2><p>O‘quv materiallari, topshiriqlar va natijalaringiz —<br className="desktop-break"/> barchasi yagona ta’lim platformasida.</p><Button asChild className="gold-button"><Link href={demo?"#materials":"/courses"}>O‘qishni davom ettirish <ArrowRight size={17}/></Link></Button></div><div className="banner-seal"><GraduationCap size={23}/><span>Bilimga yo‘l.<br/><strong>Kelajakka qadam.</strong></span></div></section>
 {error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
 <section className="stats-grid" aria-label="O‘qish ko‘rsatkichlari">{stats.map(({label,value,suffix,icon:Icon,kind})=><div className="stat-card" key={label}><div className={`stat-icon ${kind}`}><Icon size={21}/></div><div><p>{label}</p><div className="stat-value">{loading?"…":value}<span>{suffix}</span></div></div></div>)}</section>
 <div className="dashboard-columns"><div className="dashboard-primary"><section className="panel" id="materials"><div className="section-heading"><div><h2>O‘quv materiallari</h2><p>Bilimingizni boyitish uchun barcha resurslar</p></div><Link href={demo?"#materials":"/courses"}>Barchasi <ArrowRight size={15}/></Link></div><div className="material-grid">{books.slice(0,3).map((b,i)=><article className="material-card" key={b.id}><div className={`material-cover cover-${i%3}`}><div className="cover-orbit"/><BookOpen size={33} strokeWidth={1.3}/><span>MU / {String(i+1).padStart(2,"0")}</span></div><div className="material-content"><span className="subject-tag">{b.subject||"O‘quv materiali"}</span><h3>{b.title}</h3><div className="material-bottom"><span><FileText size={13}/>Darslik va resurs</span>{action(b,`/courses/${b.id}`)}</div></div></article>)}</div>{!loading&&!books.length&&<div className="empty-message"><BookOpen/>O‘qituvchingiz yuklagan materiallar shu yerda ko‘rinadi.</div>}</section>
 <section className="panel assignment-panel" id="assignments"><div className="section-heading"><div><h2>Topshiriqlar</h2><p>Muhim muddatlarni e’tibordan chetda qoldirmang</p></div><Link href={demo?"#assignments":"/assignments"}>Barchasi <ArrowRight size={15}/></Link></div><div className="assignment-head"><span>TOPSHIRIQ NOMI</span><span>MUDDAT</span><span>HOLAT</span></div>{assignments.slice(0,4).map(a=><div className="assignment-row" key={a.id}><div className="assignment-title"><div className="assignment-icon"><ClipboardList size={17}/></div><div><h3>{a.title}</h3><span>{a.is_submitted?"Javobingiz qabul qilingan":"Javob faylini yuklash kerak"}</span></div></div><div className="deadline"><Clock size={13}/>{dateLabel(a.due_date)}</div><span className={`status-badge ${a.is_submitted?"done":"pending"}`}>{a.is_submitted?<Check size={12}/>:<span className="status-dot"/>}{a.is_submitted?"Topshirilgan":"Kutilmoqda"}</span>{action(a,`/assignments/${a.id}`)}</div>)}{!loading&&!assignments.length&&<div className="empty-message"><ClipboardList/>Hozircha topshiriqlar yo‘q.</div>}</section></div>
 <aside className="dashboard-secondary"><section className="panel schedule-panel" id="schedule"><div className="section-heading"><div><h2>Yaqin jadval</h2><p>Rejalashtirilgan mashg‘ulotlar</p></div><CalendarDays size={19}/></div>{upcoming.slice(0,3).map((e,i)=><div className="schedule-item" key={e.id}><div className="schedule-time"><strong>{new Date(e.start_date).toLocaleTimeString("uz-UZ",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Tashkent"})}</strong><span>{dateLabel(e.start_date)}</span></div><div className={`schedule-detail line-${i%2}`}><span>{e.description||"Mashg‘ulot"}</span><h3>{e.title}</h3><small><Clock size={12}/>{new Date(e.end_date).toLocaleTimeString("uz-UZ",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Tashkent"})} gacha</small></div></div>)}{!loading&&!upcoming.length&&<div className="empty-message small">Yaqin tadbirlar rejalashtirilmagan.</div>}<Link className="schedule-link" href={demo?"#schedule":"/calendar"}>To‘liq taqvim <ChevronRight size={15}/></Link></section>
 <section className="panel results-panel" id="results"><div className="section-heading"><div><h2>So‘nggi natijalar</h2><p>Har bir qadam — rivojlanish</p></div><ChartNoAxesCombined size={19}/></div>{valid.slice(0,3).map(g=><div className="grade-row" key={g.id}><span className="grade-icon"><Check size={15}/></span><div><h3>{g.assignment?.title||"Topshiriq"}</h3><p>Baholangan topshiriq</p></div><strong>{g.grade}<small>/100</small></strong></div>)}{!loading&&!valid.length&&<div className="empty-message small">Baholangan ishlaringiz shu yerda ko‘rinadi.</div>}<Link className="schedule-link" href={demo?"#results":"/grades"}>Barcha natijalar <ChevronRight size={15}/></Link></section>
 <div className="quote-card"><span>“</span><p>Katta maqsadlar<br/>kichik qadamlardan<br/><strong>boshlanadi.</strong></p><div className="quote-rule"/><small>BUGUNGI ILHOM</small></div></aside></div>
 <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent><DialogHeader><DialogTitle>{detail?.title}</DialogTitle><DialogDescription>Bu dizayn namoyishidagi namunaviy ma’lumot.</DialogDescription></DialogHeader><p>{detail?.description||"Haqiqiy kabinetda o‘qituvchi yuklagan faylni shu bo‘limdan yuklab olish mumkin."}</p><Button asChild><Link href="/login">Haqiqiy kabinetga kirish <ArrowRight size={16}/></Link></Button></DialogContent></Dialog>
 </main>
}
